-- Добавление флагов оплаты/админа и статусов для сохранений
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_payment BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE saved_gradients
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'private',
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE saved_shadows
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'private',
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE saved_animations
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'private',
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
